### ISSUE TITLE
github page branch vs. master

### ISSUE THREAD

**Issue by llkats** [llkats/the-list#4]
How should we handle the github page branch vs. master? Should the gh-pages branch be the default branch? Seems like a pain to keep them separate.

**Comment by btford** [comment]
In the past, I've kept `master` and `gh-pages` in sync. I don't often use `gh-pages` to host sites so maybe my approach is sub-optimal.

**Comment by llkats** [comment]
How is it you keep them in sync? Is there an automated way you do that?

**Comment by btford** [comment]
no, just:

`git push origin master && git push origin gh-pages`

**Comment by llkats** [comment]
For future reference, push to gh-pages using `git push origin HEAD:gh-pages`.

**Comment by btford** [comment]
:+1:
