### ISSUE TITLE
Unsourced claims and lack of justification for the existence of such a list

### ISSUE THREAD

**Issue by fnordbg** [llkats/the-list#9]
First of all, let it be known that I approach this from a relatively neutral political and social perspective.

I cannot help but believe that such a list, although certainly within anyone's right to maintain and use it, is actually productive in any way. In fact, it appears quite immature and even vaguely McCarthyist.

Everyone has the right to boycott sources that they deem reprehensible, but it also helps to have justification for these actions. The tagline "these websites are bad and they should feel bad" reeks of frivolity.

It's fairly obvious that these sites are being blocked due to being offensive to a far-left postmodern world view. Yet what good does silencing out opposing view points do to offering a balanced perspective and being able to tackle objectionable opinions? I understand that one may choose not to expose themselves to uncomfortable thoughts, but it still seems unnecessarily isolationist to me. As if shutting down your ears and pretending not to listen. It's counterproductive.

But even further, the supposed transgressions that have been done here to warrant a spot in the list are very questionable. There does not seem to be any real process, either. From the repo tracker, it is evident that a pull request without a description is sufficient, and that some half-done reasoning can be tacked down later.

I have no disagreement with Valleywag being included, but not from this perspective. Valleywag is a yellow journalism tabloid that feeds on sensationalism and outrage, without offering any productive avenue for discourse in the industry it criticizes (or rather, slanders). You find the comparison of a dating site to "comfort women" to be tasteless. Yet for better or for worse, comparing certain activities to infamous historical injustices is a very common rhetorical technique. One that, indeed, people of your position also use.

But most puzzling is the inclusion of Hacker News. The justification for its inclusion is very vague. The original pull request was accepted immediately without any description being specified. The way HN is described as "an echo chamber for ignorant and divisive views" is unsourced.

It's also a complete oxymoron. An echo chamber implies that everyone shares the exact same views. For something to be divisive implies that there are multiple contentious views. A community being divisive is not a bad thing. It shows that there is diversity of opinion and an ample opportunity for proper debate.

Not to mention articles discussing issues of inequality in tech surface constantly on HN, and have plenty of people who are in agreement. Yes, there are those who offer arguments to the contrary, but they're about as equal, if not slightly outnumbered by the ones on the opposite side.

Ultimately, I have trouble reconciling the existence of this list with the goals of using technology to bring forward a more progressive society. One does not create progress by shutting themselves away, but by actively engaging.

**Comment by llkats** [comment]
Thanks for the input!

**Comment by operatorjen** [comment]
shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up shut up

**Comment by potch** [comment]
:lollipop:

**Comment by junosuarez** [comment]
PR or gtfo
